#!/usr/bin/env bash
# Script transfers files from client to server
# disp Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
# If less than 3 params transfer to ~/

PATH_TO_FILE="$1";
IP="$2";
USERNAME="$3";
PATH_TO_SSH_KEY="$4";
ERROR="Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
HOST_KEY_RULE="StrictHostKeyChecking=no"

if [ "$#" -lt 3 ]; then
	echo -e "$ERROR";
	exit 1;
fi

if [ "$#" -eq 3 ]; then
	scp -o "$HOST_KEY_RULE" "$PATH_TO_FILE" "${USERNAME}@${IP}:~/"
	exit 0;
fi

scp -o "$HOST_KEY_RULE" -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "${USERNAME}@${IP}:~/";
