#!/usr/bin/env bash
# Install nginix web server
# Listen on port 80

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello world" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx start
