#!/usr/bin/env bash
# configure nginx server
default_sites="/etc/nginx/sites-available/default"
location=$(grep -Fn location $default_sites | head -1 | cut -d":" -f1)
location_data="\\\tlocation /redirect_me {\n\t\treturn 301 https://youtu.be/mlUOUncSaTk;\n\t}\n\n"

## Perform nginx server install and config
./1-install_nginx_web_server

## Update default site to redirect and start nginx server
sudo sed -i "${location}i ${location_data}" ${default_sites}
sudo service nginx restart
