#!/usr/bin/env bash
## Perform nginx server install and config

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start;

# configure nginx server
default_sites="/etc/nginx/sites-available/default";
location=$(grep -Fn location $default_sites | head -1 | cut -d":" -f1);
location_data="\\\tlocation /redirect_me {\n\t\treturn 301 https://youtu.be/mlUOUncSaTk;\n\t}\n\n";
error_page="\\\terror_page 404 /404.html;\n";
host_name=$(hostname);
set_x_serverd_by="\\\tadd_header X-Served-By \"${host_name}\";\n";

echo "Ceci n'est pas une page" | sudo tee "/var/www/html/404.html"

## Update default site to redirect and start nginx server
sudo sed -i "${location}i ${location_data}" ${default_sites};
sudo sed -i "${location}i ${error_page}" ${default_sites};
sudo sed -i "${location}i ${set_x_serverd_by}" ${default_sites};
sudo service nginx restart;
