#!/usr/bin/env bash
# for loop in bash

FILE="/etc/passwd"

template () {
	arg="$1"
	USERNAME=$( echo -e "${arg}" | cut -d ":" -f1 )
        GROUP_ID=$( echo -e "${arg}" | cut -d ":" -f4 )
        HOME_DIRECTORY=$( echo -e "${arg}" | cut -d ":" -f6 )
        COMMAND_SHELL=$( echo -e "${arg}" | cut -d ":" -f7 )
        USER_ID=$( echo -e "${arg}" | cut -d ":" -f3 )
        PASSWORD=$( echo -e "${arg}" | cut -d ":" -f2 )
        INFO=$( echo -e "${arg}" | cut -d ":" -f5 )
        echo -e "The user ${USERNAME} is part of the ${GROUP_ID} gang, lives in ${HOME_DIRECTORY} and rides ${COMMAND_SHELL}. ${USER_ID}'s place is protected by the passcode ${PASSWORD}, more info about the user here: ${INFO}"
	}

while read -r line; do
	template "$line"
done < $FILE
