#!/usr/bin/env bash
# for loop in bash

FILE="school"

if [ -e "$FILE" ]; then
	echo -e "school file exists"
	[[ -s "$FILE" ]] && echo -e "school file is not empty"
	[[ ! -s "$FILE" ]] && echo -e "school file is empty"
	[[ -f "$FILE" ]] && echo -e "school is a regular file"

else
	echo -e "school file does not exist"
fi
